### ISSUE TITLE
Change Style/Layout of Disclaimer on Landing Page

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/fristenkalender-frontend#193]
Der Disclaimer, der in #192 eingeführt wurde, soll umgestyled werden

hier die Anforderungen: 
 
* die Horizontalen Linien sollen 2px dick sein
```css
border-bottom-width: 2px;
```
Im Text hat sich das Spacing etwas verändert
wer Tailwind nutzt hat es leicht, nur die entsprechende Farbe anpassen 
```html
class="text-hf-weiches-schwarz space-y-3 border-b-2 border-dashed border-hf-grell-rose pb-5">
```
oder plain css
```css
.text-hf-weiches-schwarz {
    --tw-text-opacity: 1;
    color: rgb(37 20 29 / var(--tw-text-opacity, 1)) /* #25141d */;
}
.space-y-3 > :not([hidden]) ~ :not([hidden]) {
    --tw-space-y-reverse: 0;
    margin-top: calc(0.75rem /* 12px */ * calc(1 - var(--tw-space-y-reverse)));
    margin-bottom: calc(0.75rem /* 12px */ * var(--tw-space-y-reverse));
}
ell-rose text-hf-weiches-schwarz pb-3 mb-5 uppercase">
.border-b-2 {
    border-bottom-width: 2px;
}
.border-dashed {
    border-style: dashed;
}
.border-hf-grell-rose {
    --tw-border-opacity: 1;
    border-color: rgb(235 190 193 / var(--tw-border-opacity, 1)) /* #ebbec1 */;
}
```
Disclaimer Text einfügen
 
CSS
DISCLAIMER: Wir geben unser Bestes, dass alle Daten korrekt und vollständig sind – können aber trotzdem nicht ausschließen, dass sich vereinzelt Fehler einschleichen. 
Layout für den Disclaimer div tailwind:
```html
class="text-hf-weiches-schwarz text-sm mt-5 opacity-50 italic
```
plain css
```css
.text-hf-weiches-schwarz {
    --tw-text-opacity: 1;
    color: rgb(37 20 29 / var(--tw-text-opacity, 1)) /* #25141d */;
}
.text-sm {
    font-size: 0.875rem /* 14px */;
    line-height: 1.25rem /* 20px */;
}
.mt-5 {
    margin-top: 1.25rem /* 20px */;
}
.opacity-50 {
    opacity: 0.5;
}
.italic {
    font-style: italic;
}
```
das Wort diclaimer hat noch ein zusatz css
tailwind
```html
class="font-medium">
```
pure css
```css
.font-medium {
    font-weight: 500;
}
```
hier noch ein Bild wie es aussieht
 
 
![grafik](https://github.com/user-attachments/assets/a69114d6-075c-44b8-8823-3d5040ddb58e)

Ihr könnt es auch gut in dem PR hier sehen: https://github.com/Hochfrequenz/ahbesser/pull/540/files
